# Generated by Django 5.1.1 on 2024-11-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="proceed",
        ),
    ]
