# Generated by Django 5.1.1 on 2024-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.CharField(max_length=2)),
                ("solution", models.CharField(max_length=400)),
                ("choice1", models.CharField(max_length=50)),
                ("choice2", models.CharField(max_length=50)),
                ("choice3", models.CharField(max_length=50)),
                ("choice4", models.CharField(max_length=51)),
                ("difficulty", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=20)),
                ("chapter", models.CharField(max_length=20)),
                ("point", models.IntegerField()),
            ],
        ),
    ]
