# Generated by Django 5.1.4 on 2025-01-08 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0003_attendacne"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attendacne",
            new_name="Attendance",
        ),
    ]
